version: '3.8'

services:
  andon_report:
    build:
      context: .
      dockerfile: Dockerfile
    image: andon_report:1.3.1
    ports:
      - "3000:3000"
    volumes:
      - /home/maganaj/volumes/andon_report/csv_files:/usr/src/app/public/csv_files
      - /home/maganaj/volumes/andon_report/config:/usr/src/app/config
    environment:
      NODE_ENV: DEV
    user: root

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "82:80" # Cambia esto si necesitas otro puerto
    depends_on:
      - andon_report
    volumes:
      - /home/maganaj/volumes/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro